### ISSUE TITLE
Issue with `geneos add host`

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#25]
Cordial v1.3.2.

Always getting error `Error: cannot open /etc/os-release or /usr/lib/os-release`.
Passwordless ssh works ok.

**Comment by gvastel** [comment]
Yes.

```
[itrs@ip-zzz-zzz-zzz-zzz ~]$ ls -ltra /etc/os-release
lrwxrwxrwx. 1 root root 21 Apr 22  2020 /etc/os-release -> ../usr/lib/os-release
[itrs@ip-zzz-zzz-zzz-zzz ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[itrs@ip-zzz-zzz-zzz-zzz ~]$ ssh xxx.xxx.xxx.xxx
Last login: Mon Nov 14 03:40:16 2022 from ip-zzz-zzz-zzz-zzz.ap-southeast-1.compute.internal
[itrs@ip-xxx-xxx-xxx-xxx ~]$ ls -ltra /etc/os-release
-rw-r--r--. 1 root root 532 Jul  3  2019 /etc/os-release
[itrs@ip-xxx-xxx-xxx-xxx ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
[itrs@ip-xxx-xxx-xxx-xxx ~]$ exit
logout
Connection to xxx.xxx.xxx.xxx closed.
[itrs@ip-zzz-zzz-zzz-zzzz ~]$

```

**Comment by gvastel** [comment]
Upon running a `geneos add -d -I <sshurl>`, I get the following ....
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8bc0a6]

goroutine 1 [running]:
github.com/itrs-group/cordial/tools/geneos/cmd.addHost(0x0?, 0x3b?)
        /home/itrs/cordial/tools/geneos/cmd/addHost.go:100 +0x26
github.com/itrs-group/cordial/tools/geneos/cmd.glob..func2(0xddce00?, {0xc000154900?, 0x1?, 0x3?})
        /home/itrs/cordial/tools/geneos/cmd/addHost.go:95 +0x1aa
github.com/spf13/cobra.(*Command).execute(0xddce00, {0xc0001548d0, 0x3, 0x3})
        /home/itrs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xde0d40)
        /home/itrs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/itrs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/itrs-group/cordial/tools/geneos/cmd.Execute()
        /home/itrs/cordial/tools/geneos/cmd/root.go:146 +0x25
main.main()
        /home/itrs/cordial/tools/geneos/main.go:46 +0x8d
```

**Comment by gvastel** [comment]
Managed to successfully create a host.
```
$ geneos add host -d -I PsApac-GvDev02 ssh://ec2-xx-xxx-xxx-xxx.ap-southeast-1.compute.amazonaws.com
2022-11-16T09:30:53Z DEBUG: tools/geneos/cmd/parseargs.go:47 cmd.parseArgs() > rawargs: [PsApac-GvDev02 ssh://ec2-xx-xxx-xxx-xxx.ap-southeast-1.compute.amazonaws.com]
2022-11-16T09:30:53Z DEBUG: tools/geneos/cmd/parseargs.go:63 cmd.parseArgs() > rawargs [PsApac-GvDev02 ssh://ec2-xx-xxx-xxx-xxx.ap-southeast-1.compute.amazonaws.com], params [], ct
2022-11-16T09:30:53Z DEBUG: tools/geneos/cmd/parseargs.go:214 cmd.cmdArgs() > map[args:["PsApac-GvDev02","ssh://ec2-xx-xxx-xxx-xxx.ap-southeast-1.compute.amazonaws.com"] ct: params:null wildcard:false] <nil>
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:121 host.(*Host).Dial() > ssh connect to ec2-xx-xxx-xxx-xxx.ap-southeast-1.compute.amazonaws.com:22 as itrs
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:32 host.readSSHkeys() > trying to read private key /home/itrs/.ssh/id_rsa
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:37 host.readSSHkeys() > read ok, parsing...
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:43 host.readSSHkeys() > loaded private key from /home/itrs/.ssh/id_rsa
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:32 host.readSSHkeys() > trying to read private key /home/itrs/.ssh/id_ecdsa
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:32 host.readSSHkeys() > trying to read private key /home/itrs/.ssh/id_ecdsa_sk
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:32 host.readSSHkeys() > trying to read private key /home/itrs/.ssh/id_ed25519
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:32 host.readSSHkeys() > trying to read private key /home/itrs/.ssh/id_ed25519_sk
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:32 host.readSSHkeys() > trying to read private key /home/itrs/.ssh/id_dsa
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:32 host.readSSHkeys() > trying to read private key
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:75 host.sshConnect() > added 1 private key(s) to auth methods
2022-11-16T09:30:53Z DEBUG: tools/geneos/internal/host/ssh.go:128 host.(*Host).Dial() > host opened PsApac-GvDev02 ec2-xx-xxx-xxx-xxx.ap-southeast-1.compute.amazonaws.com:22 itrs
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/host/ssh.go:168 host.(*Host).DialSFTP() > remote opened PsApac-GvDev02
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/downloads
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/hosts
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/licd
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/licd/licds
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/webserver
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/webserver/webservers
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/fileagent
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/fileagent/fileagents
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/downloads
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/hosts
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/gateway
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/gateway/gateways
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/gateway/gateway_shared
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/gateway/gateway_config
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/gateway/templates
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/netprobe
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/netprobe/netprobes
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/fa2
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/fa2/fa2s
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/packages/netprobe
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/san/sans
2022-11-16T09:30:54Z DEBUG: tools/geneos/internal/geneos/component.go:181 geneos.MakeComponentDirs() > mkdirall /opt/itrs/san/templates

```

**Comment by pgalbavy-itrs** [comment]
OK. EIther the recent changes have helped, or some other connectivity issue has been resolved. Closing this one.
