### ISSUE TITLE
Error encountered when copying an instance to a remote host

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#51]
This is what I got.
According to the doc, "Moving across hosts is supported".
```
$ geneos copy netprobe np_test5 np_testZ@PsApac-GvDev02
2022-11-18T02:30:37Z ERROR: tools/geneos/internal/instance/config.go:386 instance.ReadConfig() > connection to PsApac-GvDev02 failed
2022-11-18T02:30:37Z ERROR: tools/geneos/internal/instance/config.go:311 instance.writeConfig() > error="dial tcp :0: connect: connection refused"
2022-11-18T02:30:37Z ERROR: tools/geneos/internal/instance/config.go:328 instance.writeConfig() > error="dial tcp :0: connect: connection refused"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x86fe90]

goroutine 1 [running]:
github.com/pkg/sftp.(*Client).nextID(...)
        /home/itrs/go/pkg/mod/github.com/pkg/sftp@v1.13.1/client.go:264
github.com/pkg/sftp.(*Client).open(0x0, {0xc000201c80, 0x33}, 0x1a)
        /home/itrs/go/pkg/mod/github.com/pkg/sftp@v1.13.1/client.go:581 +0x30
github.com/pkg/sftp.(*Client).OpenFile(0xc0000b1220?, {0xc000201c80?, 0x9e6a6f?}, 0x9e6a6f?)
        /home/itrs/go/pkg/mod/github.com/pkg/sftp@v1.13.1/client.go:577 +0x85
github.com/spf13/afero/sftpfs.Fs.OpenFile({0x9e6a6f?}, {0xc000201c80?, 0x0?}, 0xc0000b1260?, 0x0?)
        /home/itrs/go/pkg/mod/github.com/spf13/afero@v1.9.2/sftpfs/sftp.go:100 +0x26
github.com/spf13/viper.(*Viper).writeConfig(0xc00029b380, {0xc000201c80, 0x33}, 0x1)
        /home/itrs/go/pkg/mod/github.com/spf13/viper@v1.14.0/viper.go:1674 +0x363
github.com/spf13/viper.(*Viper).WriteConfigAs(...)
        /home/itrs/go/pkg/mod/github.com/spf13/viper@v1.14.0/viper.go:1635
github.com/itrs-group/cordial/tools/geneos/internal/instance.writeConfig({0xac6408, 0xc00021cbe0})
        /home/itrs/cordial/tools/geneos/internal/instance/config.go:333 +0x36f
github.com/itrs-group/cordial/tools/geneos/internal/instance.Migrate({0xac6408, 0xc00021cbe0})
        /home/itrs/cordial/tools/geneos/internal/instance/config.go:434 +0x125
github.com/itrs-group/cordial/tools/geneos/internal/instance.WriteConfig({0xac6408, 0xc00021cbe0})
        /home/itrs/cordial/tools/geneos/internal/instance/config.go:298 +0x25
github.com/itrs-group/cordial/tools/geneos/internal/instance.CopyInstance(0xddb460, {0xc00015a4d8, 0x8}, {0xc000027f80, 0x17}, 0x0)
        /home/itrs/cordial/tools/geneos/internal/instance/copy.go:166 +0x14a5
github.com/itrs-group/cordial/tools/geneos/cmd.glob..func11(0xde07e0?, {0xc000128930?, 0x3?, 0x3?})
        /home/itrs/cordial/tools/geneos/cmd/copy.go:70 +0x165
github.com/spf13/cobra.(*Command).execute(0xde07e0, {0xc000128900, 0x3, 0x3})
        /home/itrs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xde2d40)
        /home/itrs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/itrs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/itrs-group/cordial/tools/geneos/cmd.Execute()
        /home/itrs/cordial/tools/geneos/cmd/root.go:146 +0x25
main.main()
        /home/itrs/cordial/tools/geneos/main.go:46 +0x8d
```

**Comment by pgalbavy-itrs** [comment]
The issue here was that the connection failure was logged but then the writeConfig() function continued anyway, asking the lower layers to write a file to nowhere. This has now been changed to a debug and return the error. Similar "log error and no return" have also been updated to do the same (but only in config.go for now).
